export const MAKE_MAPPING_DICT: Record<string, string[]> = {
  Aeolus: ["AEOLUS"],
  Aion: ["AION"],
  Aito: ["AITO"],
  "Alfa Romeo": ["ALFA ROMEO", "Alfa Romeo"],
  Audi: ["AUDI", "Audi"],
  Baic: ["BAIC"],
  Bmw: ["BMW", "BMW I"],
  Buick: ["BUICK", "Buick"],
  Byd: ["BYD"],
  Cadillac: ["CADILLAC", "Cadillac"],
  Changan: ["Changan", "CHANGAN"],
  Chery: ["CHERY", "Chery"],
  Chevrolet: ["Chevrolet", "CHEVROLET"],
  "Chrysle$/Jeep/Dodge": ["Chrysle$/Jeep/Dodge", "CHRYSLER/JEEP/DODGE", "CHRYSLE$/JEEP/DODGE"],
  Citroen: ["CITROEN", "Citroen"],
  Cowin: ["COWIN", "Cowin"],
  Cupra: ["CUPRA", "Cupra"],
  "Campervans Total": ["Campervans total", "Campervans Total"],
  Dacia: ["DACIA", "Dacia"],
  Deepal: ["DEEPAL", "Deepal"],
  Denza: ["DENZA", "Denza"],
  "Dongfeng Nano": ["DONGFENG NANO", "Dongfeng Nano"],
  "Dongfeng Scenery": ["Dongfeng Scenery", "DONGFENG SCENERY"],
  Dr: ["DR", "Dr"],
  Ds: ["Ds", "DS"],
  Exeed: ["EXEED", "Exeed"],
  Fiat: ["FIAT", "Fiat"],
  Ford: ["Ford", "FORD INDIA PVT LTD", "FORD"],
  Forthing: ["FORTHING", "Forthing"],
  Geely: ["GEELY", "Geely"],
  Geometry: ["GEOMETRY", "Geometry"],
  Haval: ["HAVAL", "Haval"],
  Honda: ["HONDA", "Honda", "HONDA CARS INDIA LTD"],
  Hongqi: ["HONGQI", "Hongqi"],
  Hyundai: ["HYUNDAI", "HYUNDAI MOTOR INDIA LTD", "Hyundai"],
  Iveco: ["Iveco", "IVECO"],
  Jac: ["JAC", "Jac"],
  Jaguar: ["JAGUAR", "Jaguar"],
  Jeep: ["Jeep", "JEEP"],
  Jetour: ["JETOUR", "Jetour"],
  Jetta: ["JETTA", "Jetta"],
  Kia: ["KIA MOTORS INDIA PVT LTD", "Kia", "KIA"],
  Lancia: ["LANCIA", "Lancia"],
  "Land Rover": ["Land Rover", "LAND ROVER"],
  Leapmotor: ["Leapmotor", "LEAPMOTOR"],
  Lexus: ["LEXUS", "TOYOTA/LEXUS", "Lexus"],
  Li: ["LI", "Li"],
  Lincoln: ["Lincoln", "LINCOLN"],
  Lynk: ["Lynk", "LYNK"],
  "Lynk&Co": ["Lynk&Co", "LYNK&CO"],
  "Mahindra & Mahindra Limited": ["Mahindra & Mahindra Limited", "MAHINDRA & MAHINDRA LIMITED"],
  "Maruti Suzuki India Ltd": ["MARUTI SUZUKI INDIA LTD", "Maruti Suzuki India Ltd"],
  Maxus: ["Maxus", "MAXUS"],
  Mazda: ["Mazda", "MAZDA"],
  Mercedes: ["Mercedes", "MERCEDES-BENZ INDIA PVT LTD", "MERCEDES", "MERCEDES-BENZ"],
  Mg: ["MG MOTOR INDIA PVT LTD", "MG"],
  "Mg Roewe": ["Mg Roewe", "MG ROEWE"],
  Mini: ["MINI", "Mini"],
  Mitsubishi: ["MITSUBISHI", "Mitsubishi"],
  Neta: ["Neta", "NETA"],
  Nio: ["Nio", "NIO"],
  Nissan: ["NISSAN", "Nissan", "NISSAN MOTOR INDIA PVT LTD"],
  Opel: ["OPEL", "Opel"],
  Ora: ["Ora", "ORA"],
  Oshan: ["OSHAN", "Oshan"],
  Others: ["OTHERS", "Others"],
  Pentium: ["Pentium", "PENTIUM"],
  Peugeot: ["PEUGEOT", "Peugeot"],
  Polestar: ["Polestar", "POLESTAR"],
  Porsche: ["PORSCHE", "Porsche"],
  Renault: ["RENAULT INDIA PVT LTD", "RENAULT", "Renault"],
  Roewe: ["ROEWE", "Roewe"],
  Saab: ["Saab", "SAAB"],
  Seat: ["Seat", "SEAT"],
  Sehol: ["SEHOL", "Sehol"],
  Skoda: ["SKODA", "SKODA AUTO VOLKSWAGEN INDIA PVT LTD", "Skoda"],
  Smart: ["Smart", "SMART"],
  Sonstige: ["Sonstige", "SONSTIGE"],
  Suzuki: ["SUZUKI", "Suzuki"],
  Tank: ["TANK", "Tank"],
  "Tata Motors Ltd": ["TATA MOTORS LTD", "TATA MOTORS PASSENGER VEHICLES LTD", "Tata Motors Ltd"],
  Tesla: ["TESLA", "Tesla Motors", "Tesla"],
  Toyota: ["TOYOTA", "Toyota", "TOYOTA KIRLOSKAR MOTOR PVT LTD"],
  Trumpchi: ["Trumpchi", "TRUMPCHI"],
  Vauxhall: ["Vauxhall", "VAUXHALL"],
  Venucia: ["VENUCIA", "Venucia"],
  Volkswagen: ["Volkswagen", "VOLKSWAGEN", "Vw", "VOLKSWAGEN INDIA PVT LTD"],
  Volvo: ["Volvo", "VOLVO"],
  Wuling: ["Wuling", "WULING"],
  Xpeng: ["XPENG", "Xpeng"],
  Zeekr: ["ZEEKR", "Zeekr"],
};

export const MAKE_OPTIONS = Object.keys(MAKE_MAPPING_DICT).sort();
